---
abstract: 'Scala scale support for Perl'
author:
  - 'Jeremy Mates <jmates@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Music-Scala
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0
resources:
  homepage: http://github.com/thrig/Music-Scala
  license: http://dev.perl.org/licenses/
  repository: http://github.com/thrig/Music-Scala
version: 0.60
